INSERT INTO `Field` (`Field_id`,`name`) VALUES (1,'Maths');
INSERT INTO `Field` (`Field_id`,`name`) VALUES (2,'Physics');
INSERT INTO `Field` (`Field_id`,`name`) VALUES (3,'IT');
INSERT INTO `Field` (`Field_id`,`name`) VALUES (4,'History');
INSERT INTO `Field` (`Field_id`,`name`) VALUES (5,'Archaeology');
INSERT INTO `Field` (`Field_id`,`name`) VALUES (6,'Environment');
INSERT INTO `Field` (`Field_id`,`name`) VALUES (7,'Biology');
INSERT INTO `Field` (`Field_id`,`name`) VALUES (8,'Social Science');
INSERT INTO `Field` (`Field_id`,`name`) VALUES (9,'Law');
INSERT INTO `Field` (`Field_id`,`name`) VALUES (10,'Geology');
INSERT INTO `Field` (`Field_id`,`name`) VALUES (11,'Politics');
INSERT INTO `Field` (`Field_id`,`name`) VALUES (12,'Chemistry');