INSERT INTO `Program` (`name`,`sector`) VALUES ('Environmental Preservation Program','Environmental Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Database Development Program','IT Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Recycling Program','Environmental Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Pharmaceutical Research Program','Biology Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Light and Lasers Technologies Program','Technologies Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Machine Learning Program','IT Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Renewable Energy Sources Program','Environmental Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Algorithms Program','Mathemetics Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Law Enforcement Program','Law Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Road Development Program','Infrastracture Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Building Preservation','Infrastracture Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Wind Park Development Program','Environmental Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Water Waste Reduction Program','Biology Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Earthquake Research Program','Enviromental Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Artificial Inteligence Development Program','IT Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Solar Energy Ifrastructure Program','Environmental Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Mathematics Department Update Program','Mathemetics Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Biological Crop Facilities Program','Enviromental Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Advanced Technologies Program','Technologies Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Software Development Program','IT Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Recycling Materials Program','Environmental Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Microbiologies Technologies Program','Biology Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('National Parks Renovation Program','Enviromental Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Computer Applications on Arcitecture Program','IT Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Neural Networks Program','Technologies Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Robotic Facilities Program','Technologies Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Modern Antennas Program','Technologies Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('National Forests Preservation Program','Environmental Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Advanced Database Systems Development Program','IT Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Applied Robotics Technologies Program','Technologies Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Viruses and Pandemics Program','Biology Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Enhanced Performance Technologies Program','Technologies Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Software for Smart Cars Program','IT Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Smart Cities Program','Environmental Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Applied Mathemetics Program','Mathemetics Sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Transportation Infrastracture Program','Technologies Sector');
