UPDATE Projects SET Title = 'Επανασχεδιασμένη στάση πελάτη-εξυπηρετητή' WHERE Project_id = 1;
UPDATE Projects SET Title = 'Διαχείριση ενδιάμεσων προβλέψεων' WHERE Project_id = 2;
UPDATE Projects SET Title = 'Βελτίωση της κινητής ομάδας εργασίας' WHERE Project_id = 3;
UPDATE Projects SET Title = 'Οραματικό συστημικό τοπικό δίκτυο' WHERE Project_id = 4;
UPDATE Projects SET Title = 'Προληπτική υποστήριξη 4ης γενιάς' WHERE Project_id = 5;
UPDATE Projects SET Title = 'Ενισχυμένη συστηματική τυποποίηση' WHERE Project_id = 6;
UPDATE Projects SET Title = 'Αποκλειστικές εκτελεστικές λειτουργίες' WHERE Project_id = 7;
UPDATE Projects SET Title = 'Ισορροπημένη υποστήριξη πελάτη-εξυπηρετητή' WHERE Project_id = 8;
UPDATE Projects SET Title = 'Αφομοιωμένη πρόβλεψη με βάση το πλαίσιο' WHERE Project_id = 9;
UPDATE Projects SET Title = 'Επαναπροσδιορισμένος αλγόριθμος υποβάθρου' WHERE Project_id = 10;
UPDATE Projects SET Title = 'Ευέλικτη ριζοσπαστική αντίληψη' WHERE Project_id = 11;
UPDATE Projects SET Title = 'Τριπλό ρυθμιστικό πλέγμα προσαύξησης' WHERE Project_id = 12;
UPDATE Projects SET Title = 'Ομαδική κλιμακούμενη συσσωμάτωση' WHERE Project_id = 13;
UPDATE Projects SET Title = 'Αυτόνομοι ασύγχρονοι πίνακες' WHERE Project_id = 14;
UPDATE Projects SET Title = 'Πελατοκεντρικό περιεκτικό πλαίσιο' WHERE Project_id = 15;
UPDATE Projects SET Title = 'Πρόσωπο με πρόσωπο ρητή πρόβλεψη' WHERE Project_id = 16;
UPDATE Projects SET Title = 'Κλιμακούμενη πολυπλοκότητα σε επίπεδο βάσης' WHERE Project_id = 17;
UPDATE Projects SET Title = 'Πρόσωπο με πρόσωπο προσανατολισμένη στη λύση απόδοση' WHERE Project_id = 18;
UPDATE Projects SET Title = 'Κοινόχρηστη κινητή γραφική διεπαφή' WHERE Project_id = 19;
UPDATE Projects SET Title = 'Διαφορετικό ουδέτερο εργατικό δυναμικό' WHERE Project_id = 20;
UPDATE Projects SET Title = 'Καθολική περιφερειακή εξομοίωση' WHERE Project_id = 21;
UPDATE Projects SET Title = 'Προσαρμόσιμη μήτρα πολυμέσων' WHERE Project_id = 22;
UPDATE Projects SET Title = 'Ευελιξία αποσυνδεδεμένου ανοικτού κώδικα' WHERE Project_id = 23;
UPDATE Projects SET Title = 'Παρακολουθούμενος σύνθετος αναλυτής' WHERE Project_id = 24;
UPDATE Projects SET Title = 'Υποχρεωτική γραφική διεπαφή υποβάθρου' WHERE Project_id = 25;
UPDATE Projects SET Title = 'Ενισχυμένο σύνολο εργαλείων λογιστικής' WHERE Project_id = 26;
UPDATE Projects SET Title = 'Χρήστης υβριδικών γνώσεων με τριπλή απομόνωση' WHERE Project_id = 27;
UPDATE Projects SET Title = 'Διασυνοριακή ενδυναμωτική πρόκληση' WHERE Project_id = 28;
UPDATE Projects SET Title = 'Εναλλασσόμενη τεχνητή νοημοσύνη με γνώμονα τον πελάτη' WHERE Project_id = 29;
UPDATE Projects SET Title = 'Προγραμματιζόμενο επιδραστικό ενδιάμεσο λογισμικό' WHERE Project_id = 30;
UPDATE Projects SET Title = 'Μειωμένη καλά διαμορφωμένη στρατηγική' WHERE Project_id = 31;
UPDATE Projects SET Title = 'Επικεντρωμένη αυξητική γραφική διεπαφή' WHERE Project_id = 32;
UPDATE Projects SET Title = 'Σταδιακή μη πτητική αρχιτεκτονική' WHERE Project_id = 33;
UPDATE Projects SET Title = 'Αποκλειστική συνεκτική επιτυχία' WHERE Project_id = 34;
UPDATE Projects SET Title = 'Αφομοιωμένο ενδιάμεσο χρονοδιάγραμμα' WHERE Project_id = 35;
UPDATE Projects SET Title = 'Βελτιωμένη σύνθετη υποστήριξη αιολίκων πάρκων' WHERE Project_id = 36;
UPDATE Projects SET Title = 'Ανοιχτή βάση γνώσης πελάτη-διακομιστή' WHERE Project_id = 37;
UPDATE Projects SET Title = 'Καινοτόμο εθνικό intranet' WHERE Project_id = 38;
UPDATE Projects SET Title = 'Διαισθητική δικτυακή πύλη με ευαισθησία στα συμφραζόμενα' WHERE Project_id = 39;
UPDATE Projects SET Title = 'Λογισμικό δημόσιου κλειδιού' WHERE Project_id = 40;
UPDATE Projects SET Title = 'Εργονομική σταθερή βελτίωση της διαδικασίας' WHERE Project_id = 41;
UPDATE Projects SET Title = 'Προληπτικό επεκτάσιμο extranet' WHERE Project_id = 42;
UPDATE Projects SET Title = 'Πρόσωπο με πρόσωπο που αποπνέει ορισμό' WHERE Project_id = 43;
UPDATE Projects SET Title = 'Ασφαλής ασύμμετρη κωδικοποίηση' WHERE Project_id = 44;
UPDATE Projects SET Title = 'Πολυκαναλική ικανότητα πολλαπλών καταστάσεων' WHERE Project_id = 45;
UPDATE Projects SET Title = 'Επίμονος πυρήνας 5ης γενιάς' WHERE Project_id = 46;
UPDATE Projects SET Title = 'Ουδέτερη γραφική διεπαφή χρήστη που ενεργοποιείται μόνη της' WHERE Project_id = 47;
UPDATE Projects SET Title = 'Μεθοδολογία πολωμένης μηδενικής ανοχής' WHERE Project_id = 48;
UPDATE Projects SET Title = 'Συστημικές λειτουργικότητες βασισμένες σε αντικείμενα' WHERE Project_id = 49;
UPDATE Projects SET Title = 'Δευτερεύον αρχείο ανοικτού κώδικα' WHERE Project_id = 50;
UPDATE Projects SET Title = 'Μεθοδική παρακολούθηση με επίκεντρο την ποιότητα' WHERE Project_id = 51;
UPDATE Projects SET Title = 'Διακριτή επιτυχία' WHERE Project_id = 52;
UPDATE Projects SET Title = 'Διευρυμένη στάση μηδενικής ανοχής' WHERE Project_id = 53;
UPDATE Projects SET Title = 'Προληπτικό αποκλειστικό ανοικτό σύστημα' WHERE Project_id = 54;
UPDATE Projects SET Title = 'Προληπτική αρθρωτή μόχλευση' WHERE Project_id = 55;
UPDATE Projects SET Title = 'Προσανατολισμένο στον πελάτη κρίσιμο χρονικό πλαίσιο αποστολής' WHERE Project_id = 56;
UPDATE Projects SET Title = 'Επαναπροσδιορισμένο σταδιακό ανοικτό σύστημα' WHERE Project_id = 57;
UPDATE Projects SET Title = 'Διευρυμένη μήτρα αιχμής' WHERE Project_id = 58;
UPDATE Projects SET Title = 'Πολυμερής αμφίδρομη αποθήκη δεδομένων' WHERE Project_id = 59;
UPDATE Projects SET Title = 'Νευρωνικό δίκτυο μηδενικών ελαττωμάτων ανοικτού κώδικα' WHERE Project_id = 60;
UPDATE Projects SET Title = 'Οργανικό διαδραστικό χρονικό πλαίσιο' WHERE Project_id = 61;
UPDATE Projects SET Title = 'Αυτόνομο εργατικό δυναμικό πολλαπλών εργασιών' WHERE Project_id = 62;
UPDATE Projects SET Title = 'Αποκεντρωμένη παγκόσμια υποδομή' WHERE Project_id = 63;
UPDATE Projects SET Title = 'Βελτιστοποιημένη πρόβλεψη πελάτη-εξυπηρετητή' WHERE Project_id = 64;
UPDATE Projects SET Title = 'Καθολικός παραλληλισμός 3ης γενιάς' WHERE Project_id = 65;
UPDATE Projects SET Title = 'Αναβαθμίσιμη βελτίωση της διαδικασίας με τη βοήθεια πλέγματος' WHERE Project_id = 66;
UPDATE Projects SET Title = 'Μηχανή συστήματος ενεργοποίησης ανοικτής αρχιτεκτονικής' WHERE Project_id = 67;
UPDATE Projects SET Title = 'Συμβατός μεγιστοποιημένος αναλυτής' WHERE Project_id = 68;
UPDATE Projects SET Title = 'Πολυκατευθυνόμενο οικοκεντρικό γραφείο εξυπηρέτησης' WHERE Project_id = 69;
UPDATE Projects SET Title = 'Δικτυωμένο ομοιογενές πλαίσιο' WHERE Project_id = 70;
UPDATE Projects SET Title = 'Βαθιά δευτερεύουσα ενορχήστρωση' WHERE Project_id = 71;
UPDATE Projects SET Title = 'Αποκλειστικό ενδοδίκτυο μηδενικών ελαττωμάτων' WHERE Project_id = 72;
UPDATE Projects SET Title = 'Κοινοποιήσιμη ρητή εφαρμογή' WHERE Project_id = 73;
UPDATE Projects SET Title = 'Τοπικό δίκτυο πολυμέσων πρώτης γραμμής' WHERE Project_id = 74;
UPDATE Projects SET Title = 'Ευθυγραμμισμένος παραλληλισμός με ευαισθησία στο πλαίσιο' WHERE Project_id = 75;
UPDATE Projects SET Title = 'Παρακολούθηση προσανατολισμένη στη στάση' WHERE Project_id = 76;
UPDATE Projects SET Title = 'Πολυεπίπεδη ολιστική διεπαφή' WHERE Project_id = 77;
UPDATE Projects SET Title = 'Χρηστοκεντρικό σύνολο εντολών με ανοδική τάση' WHERE Project_id = 78;
UPDATE Projects SET Title = 'Ομαδικό σπονδυλωτό λογισμικό' WHERE Project_id = 79;
UPDATE Projects SET Title = 'Ενορχήστρωση με γνώμονα τον πελάτη.' WHERE Project_id = 80;
UPDATE Projects SET Title = 'Συνεργιστική μεθοδική υλοποίηση' WHERE Project_id = 81;
UPDATE Projects SET Title = 'Διαφορετική μηδενική ανοχή' WHERE Project_id = 82;
UPDATE Projects SET Title = 'Προσαρμοστικός αλγόριθμος ανοχής σφαλμάτων' WHERE Project_id = 83;
UPDATE Projects SET Title = 'Λειτουργικός κόμβος κρίσιμης αποστολής' WHERE Project_id = 84;
UPDATE Projects SET Title = 'Συνεργατική ομάδα εστίασης με βάση το πλαίσιο' WHERE Project_id = 85;
UPDATE Projects SET Title = 'Επανασυνδεδεμένο προϋπάρχον υλικό' WHERE Project_id = 86;
UPDATE Projects SET Title = 'Συνεργαζόμενη βάση δεδομένων πολυμέσων' WHERE Project_id = 87;
UPDATE Projects SET Title = 'Εκτεταμένη ανάλυση προβολής' WHERE Project_id = 88;
UPDATE Projects SET Title = 'Λογισμικό υψηλού επιπέδου με επίκεντρο την ποιότητα' WHERE Project_id = 89;
UPDATE Projects SET Title = 'Διαφορετικό αρχείο με δυνατότητα διαδικτύου' WHERE Project_id = 90;
UPDATE Projects SET Title = 'Παρακίνηση της παραγωγικότητας σε πολλαπλές πλατφόρμες' WHERE Project_id = 91;
UPDATE Projects SET Title = 'Καθολικός μηχανισμός συστημικού συστήματος' WHERE Project_id = 92;
UPDATE Projects SET Title = 'Ενισχυμένη πύλη βασισμένη σε συμφραζόμενα' WHERE Project_id = 93;
UPDATE Projects SET Title = 'Αυτόνομη συνεκτική στάση' WHERE Project_id = 94;
UPDATE Projects SET Title = 'Ενισχυμένο ομαδικό λογισμικό μηδενικών ελαττωμάτων' WHERE Project_id = 95;
UPDATE Projects SET Title = 'Παραλληλισμός βασισμένος στις ανάγκες με επίκεντρο το κέρδος' WHERE Project_id = 96;
UPDATE Projects SET Title = 'Κεντρικοποιημένος ασύμμετρος αλγόριθμος' WHERE Project_id = 97;
UPDATE Projects SET Title = 'Εστιασμένη πρωτοβουλία ανταπόκρισης' WHERE Project_id = 98;
UPDATE Projects SET Title = 'Συνεργιστικός υβριδικός συντονιστής' WHERE Project_id = 99;
UPDATE Projects SET Title = 'Κατανεμημένη ευρετική λειτουργία' WHERE Project_id = 100;
UPDATE Projects SET Title = 'Φιλικό προς το χρήστη, με σαφή σκέψη, ομαδικό λογισμικό' WHERE Project_id = 101;
UPDATE Projects SET Title = 'Κλωνοποιημένη ικανότητα κρίσιμης αποστολής' WHERE Project_id = 102;
UPDATE Projects SET Title = 'Αποκεντρωμένο σύνολο λογιστικών εργαλείων' WHERE Project_id = 103;
UPDATE Projects SET Title = 'Εικονική μεθοδολογία κατώτατης γραμμής' WHERE Project_id = 104;
UPDATE Projects SET Title = 'Προληπτικός ρητός παραλληλισμός' WHERE Project_id = 105;
UPDATE Projects SET Title = 'Επαναπροσδιορισμένο ουδέτερο πλαίσιο' WHERE Project_id = 106;
UPDATE Projects SET Title = 'Εργαλειοθήκη μηδενικής ανοχής σε επίπεδο βάσης' WHERE Project_id = 107;
UPDATE Projects SET Title = 'Ομαδικό παγκόσμιο γραφείο εξυπηρέτησης' WHERE Project_id = 108;
UPDATE Projects SET Title = 'Πολωμένο μεταβατικό ενδιάμεσο λογισμικό' WHERE Project_id = 109;
UPDATE Projects SET Title = 'Ισορροπημένη ρητή υλοποίηση' WHERE Project_id = 110;
UPDATE Projects SET Title = 'Επιχειρησιακός ενδυναμωτικός παραλληλισμός' WHERE Project_id = 111;
UPDATE Projects SET Title = 'Υβριδική γραφική διεπαφή χρήστη με τριπλή απομόνωση' WHERE Project_id = 112;
UPDATE Projects SET Title = 'Οργανικός δικτυακός τόπος κρίσιμης αποστολής' WHERE Project_id = 113;
UPDATE Projects SET Title = 'Μελλοντικά εξασφαλισμένη συνεκτική λειτουργία' WHERE Project_id = 114;
UPDATE Projects SET Title = 'Φιλική προς τον χρήστη πρόκληση με γνώμονα τον πελάτη' WHERE Project_id = 115;
UPDATE Projects SET Title = 'Ομοιογενές προϊόν πολλαπλών επιπέδων' WHERE Project_id = 116;
UPDATE Projects SET Title = 'Προγραμματιζόμενο ομαδικό λογισμικό κρίσιμης αποστολής' WHERE Project_id = 117;
UPDATE Projects SET Title = 'Πολυμερής διεπαφή με γνώμονα τον πελάτη' WHERE Project_id = 118;
UPDATE Projects SET Title = 'Κεντρική ανταποκρινόμενη εξομοίωση' WHERE Project_id = 119;
UPDATE Projects SET Title = 'Διαχειριζόμενη ανοικτή αρχιτεκτονική πλήρους φάσματος' WHERE Project_id = 120;
UPDATE Projects SET Title = 'Προγραμματιζόμενη προσέγγιση βελτιστοποίησης' WHERE Project_id = 121;
UPDATE Projects SET Title = 'Συστηματικός κόμβος πολλαπλών πλατφορμών' WHERE Project_id = 122;
UPDATE Projects SET Title = 'Κεντρικοποιημένη υβριδική πρόσβαση' WHERE Project_id = 123;
UPDATE Projects SET Title = 'Βελτιωμένη γραφική διεπαφή με βάση τις ανάγκες' WHERE Project_id = 124;
UPDATE Projects SET Title = 'Εξασφαλισμένο εκτελεστικό έργο' WHERE Project_id = 125;
UPDATE Projects SET Title = 'Παρακολουθούμενο τοπικό intranet' WHERE Project_id = 126;
UPDATE Projects SET Title = 'Αυτοματοποιημένη ασφαλής γραμμή με ανοχή σε σφάλματα' WHERE Project_id = 127;
UPDATE Projects SET Title = 'Ασφαλής γραμμή κινητών τηλεφώνων με επίκεντρο τις επιχειρήσεις' WHERE Project_id = 128;
UPDATE Projects SET Title = 'Καθολική διακριτή λειτουργία' WHERE Project_id = 129;
UPDATE Projects SET Title = 'Χωρητικότητα σε πραγματικό χρόνο με επίκεντρο τον πελάτη' WHERE Project_id = 130;
UPDATE Projects SET Title = 'Βελτιστοποιημένη κινητή παρακολούθηση' WHERE Project_id = 131;
UPDATE Projects SET Title = 'Κοινόχρηστος ριζοσπαστικός προσαρμογέας' WHERE Project_id = 132;
UPDATE Projects SET Title = 'Προσαρμοστική συγκέντρωση ανθρώπινων πόρων' WHERE Project_id = 133;
UPDATE Projects SET Title = 'Τριπλά αποθηκευμένη ικανότητα αξιοπρεπούς συστήματος' WHERE Project_id = 134;
UPDATE Projects SET Title = 'Αποκεντρωμένος παραλληλισμός πολλαπλών καταστάσεων' WHERE Project_id = 135;
UPDATE Projects SET Title = 'Προηγμένη ικανότητα με βάση τη ζήτηση' WHERE Project_id = 136;
UPDATE Projects SET Title = 'Συστηματική μόχλευση με βάση τη λειτουργία' WHERE Project_id = 137;
UPDATE Projects SET Title = 'Σταδιακή διδακτική ενορχήστρωση' WHERE Project_id = 138;
UPDATE Projects SET Title = 'Καινοτόμος εκτελεστική μόχλευση' WHERE Project_id = 139;
UPDATE Projects SET Title = 'Πολυεπίπεδη αποδιαμεσολάβηση' WHERE Project_id = 140;
UPDATE Projects SET Title = 'Εφαρμοσμένο κύκλωμα με δυνατότητα διαδικτύου' WHERE Project_id = 141;
UPDATE Projects SET Title = 'Διχασμένη χρήση με επίκεντρο τον χρήστη' WHERE Project_id = 142;
UPDATE Projects SET Title = 'Δικτυωμένη σπονδυλωτή διαχείριση του προϋπολογισμού' WHERE Project_id = 143;
UPDATE Projects SET Title = 'Ενορχήστρωση 3ης γενιάς με επίκεντρο τον πελάτη' WHERE Project_id = 144;
UPDATE Projects SET Title = 'Προηγμένος μη πτητικός πυρήνας' WHERE Project_id = 145;
UPDATE Projects SET Title = 'Κατανεμημένη ομάδα εστίασης 3ης γενιάς' WHERE Project_id = 146;
UPDATE Projects SET Title = 'Πολωμένη περιβάλλουσα ασφαλής γραμμή' WHERE Project_id = 147;
UPDATE Projects SET Title = 'Υποχρεωτική στρατηγική παρακίνησης' WHERE Project_id = 148;
UPDATE Projects SET Title = 'Υποχρεωτικό ενδιάμεσο λογισμικό πραγματικού χρόνου' WHERE Project_id = 149;
UPDATE Projects SET Title = 'Ομαδική εγκατάσταση πολλαπλών καταστάσεων' WHERE Project_id = 150;
UPDATE Projects SET Title = 'Βελτιστοποιημένη κλιμακούμενη λειτουργία' WHERE Project_id = 151;
UPDATE Projects SET Title = 'Κρυπτογράφηση υλικοτεχνικής υποδομής χαμηλού μεγέθους' WHERE Project_id = 152;
UPDATE Projects SET Title = 'Αντίστροφη συνεργασία φρέσκιας σκέψης' WHERE Project_id = 153;
UPDATE Projects SET Title = 'Εναλλασσόμενο αυξητικό ενδεχόμενο' WHERE Project_id = 154;
UPDATE Projects SET Title = 'Επίμονη λειτουργία πολυμέσων' WHERE Project_id = 155;
UPDATE Projects SET Title = 'Ομαδική ουδέτερη προβολή' WHERE Project_id = 156;
UPDATE Projects SET Title = 'Πολυμερής στατική αποθήκη δεδομένων' WHERE Project_id = 157;
UPDATE Projects SET Title = 'Αυτόνομη τεχνητή νοημοσύνη κατώτατης γραμμής' WHERE Project_id = 158;
UPDATE Projects SET Title = 'Συνεργαζόμενη αρχιτεκτονική συστήματος' WHERE Project_id = 159;
UPDATE Projects SET Title = 'Λειτουργικό ομοιογενές παράδειγμα' WHERE Project_id = 160;
UPDATE Projects SET Title = 'Πλήρως παραμετροποιήσιμη οικοκεντρική γραφική διεπαφή' WHERE Project_id = 161;
UPDATE Projects SET Title = 'Πρωτόκολλο πελάτη με δημόσιο κλειδί' WHERE Project_id = 162;
UPDATE Projects SET Title = 'Προγραμματιζόμενη παραγωγικότητα κατώτατης γραμμής' WHERE Project_id = 163;
UPDATE Projects SET Title = 'Εξορθολογισμένη τριτογενής λειτουργία' WHERE Project_id = 164;
UPDATE Projects SET Title = 'Κλωνοποιημένο ενδεχόμενο πολλαπλών εργασιών' WHERE Project_id = 165;
UPDATE Projects SET Title = 'Διαφορετική καλά διαμορφωμένη δομή' WHERE Project_id = 166;
UPDATE Projects SET Title = 'Αντιδραστική μεθοδολογία με γνώμονα τον πελάτη' WHERE Project_id = 167;
UPDATE Projects SET Title = 'Τριπλά ρυθμισμένη ριζική αποθήκη δεδομένων' WHERE Project_id = 168;
UPDATE Projects SET Title = 'Ομάδα εστίασης ανοικτού κώδικα με δυνατότητα πλέγματος' WHERE Project_id = 169;
UPDATE Projects SET Title = 'Διευρυμένη μη πτητική ευελιξία' WHERE Project_id = 170;
UPDATE Projects SET Title = 'Αναβαθμίσιμος τριτογενής συντονιστής' WHERE Project_id = 171;
UPDATE Projects SET Title = 'Δευτερεύουσα εφαρμογή με επίκεντρο το κέρδος' WHERE Project_id = 172;
UPDATE Projects SET Title = 'Εστιασμένο ολιστικό σύνολο εντολών' WHERE Project_id = 173;
UPDATE Projects SET Title = 'Διαφορετική ασύγχρονη ενορχήστρωση' WHERE Project_id = 174;
UPDATE Projects SET Title = 'Βαθιά διακριτή συμμαχία' WHERE Project_id = 175;
UPDATE Projects SET Title = 'Επίμονος ομοιογενής αναλυτής' WHERE Project_id = 176;
UPDATE Projects SET Title = 'Ενδιάμεση υπηρεσία-υποδοχή μεγάλου μεγέθους' WHERE Project_id = 177;
UPDATE Projects SET Title = 'Αποκεντρωμένη συνεργασία κρίσιμης αποστολής' WHERE Project_id = 178;
UPDATE Projects SET Title = 'Αυτόνομη ανοικτή αρχιτεκτονική προσανατολισμένη στη λύση' WHERE Project_id = 179;
UPDATE Projects SET Title = 'Κερδοσκοπικό ενδιάμεσο ενδιάμεσο λογισμικό' WHERE Project_id = 180;
UPDATE Projects SET Title = 'Υλοποίηση βάσης με γνώμονα τη ζήτηση' WHERE Project_id = 181;
UPDATE Projects SET Title = 'Στιβαρή αποθήκη δεδομένων με ομοιόμορφο άξονα' WHERE Project_id = 182;
UPDATE Projects SET Title = 'Κωδικοποίηση με βάση το περιεχόμενο' WHERE Project_id = 183;
UPDATE Projects SET Title = 'Ρητή γραφική διεπαφή χρήστη δημόσιου κλειδιού' WHERE Project_id = 184;
UPDATE Projects SET Title = 'Υβριδική υπερδομή βασισμένη σε αντικείμενα' WHERE Project_id = 185;
UPDATE Projects SET Title = 'Τριτογενές έργο ανοικτής αρχιτεκτονικής' WHERE Project_id = 186;
UPDATE Projects SET Title = 'Ψηφιοποιημένη περιεκτική ανοικτή αρχιτεκτονική' WHERE Project_id = 187;
UPDATE Projects SET Title = 'Αντιδραστική διακριτή πρόκληση' WHERE Project_id = 188;
UPDATE Projects SET Title = 'Σταδιακή διαιρεμένη πρόβλεψη' WHERE Project_id = 189;
UPDATE Projects SET Title = 'Συγχρονισμένη προσέγγιση με χρήση πλέγματος' WHERE Project_id = 190;
UPDATE Projects SET Title = 'Προηγμένος ουδέτερος αλγόριθμος' WHERE Project_id = 191;
UPDATE Projects SET Title = 'Τοπική ιεραρχία με επίκεντρο τον πελάτη' WHERE Project_id = 192;
UPDATE Projects SET Title = 'Διαφορετικός περιφερειακός κόμβος' WHERE Project_id = 193;
UPDATE Projects SET Title = 'Αντίστροφη διχασμένη πρόβλεψη' WHERE Project_id = 194;
UPDATE Projects SET Title = 'Αυτοματοποιημένο διδακτικό τοπικό δίκτυο' WHERE Project_id = 195;
UPDATE Projects SET Title = 'Κεντρική ικανότητα προσανατολισμένη στη λύση' WHERE Project_id = 196;
UPDATE Projects SET Title = 'Αναπροσαρμοσμένο αρχείο που παρακολουθείται από το εύρος ζώνης' WHERE Project_id = 197;
UPDATE Projects SET Title = 'Οριζόντια συστηματική ικανότητα' WHERE Project_id = 198;
UPDATE Projects SET Title = 'Συστηματική πρόβλεψη σε μικρότερο μέγεθος' WHERE Project_id = 199;
UPDATE Projects SET Title = 'Αυτόνομη ικανότητα πλήρους φάσματος' WHERE Project_id = 200;
UPDATE Projects SET Title = 'Βελτιστοποιημένη πρόκληση ενεργοποίησης' WHERE Project_id = 201;
UPDATE Projects SET Title = 'Μετάβαση στη μηδενική διαχείριση διασταυρούμενων ομάδων' WHERE Project_id = 202;
UPDATE Projects SET Title = 'Ισορροπημένη δυναμική προσέγγιση' WHERE Project_id = 203;
UPDATE Projects SET Title = 'Εργονομικό γραφείο υπηρεσιών προστιθέμενης αξίας' WHERE Project_id = 204;
UPDATE Projects SET Title = 'Συνολικό μη πτητικό λογισμικό' WHERE Project_id = 205;
UPDATE Projects SET Title = 'Ομοιογενής ιεραρχία με επίκεντρο το κέρδος' WHERE Project_id = 206;
UPDATE Projects SET Title = 'Επανασχεδιασμένη ομοιόμορφη πρόβλεψη' WHERE Project_id = 207;
UPDATE Projects SET Title = 'Προληπτική κατευθυντική ιστοσελίδα' WHERE Project_id = 208;
UPDATE Projects SET Title = 'Εναλλασσόμενο παγκόσμιο παράδειγμα' WHERE Project_id = 209;
UPDATE Projects SET Title = 'Συνολικό δευτερεύον προϊόν' WHERE Project_id = 210;
UPDATE Projects SET Title = 'Εξορθολογισμένος αλγόριθμος 6ης γενιάς' WHERE Project_id = 211;
UPDATE Projects SET Title = 'Βαθύς μηχανισμός συστήματος πολλαπλών εργασιών' WHERE Project_id = 212;
UPDATE Projects SET Title = 'Μεταβατική ομάδα εστίασης με επίκεντρο τον χρήστη' WHERE Project_id = 213;
UPDATE Projects SET Title = 'Αποκλειστική διαδραστική απόδοση' WHERE Project_id = 214;
UPDATE Projects SET Title = 'Ισορροπημένο κύκλωμα πελάτη-εξυπηρετητή' WHERE Project_id = 215;
UPDATE Projects SET Title = 'Εξορθολογισμένη οικοκεντρική συσσωμάτωση' WHERE Project_id = 216;
UPDATE Projects SET Title = 'Λειτουργικός σταθερός αναλυτής' WHERE Project_id = 217;
UPDATE Projects SET Title = 'Συνεκτική στρατηγική σωστού μεγέθους' WHERE Project_id = 218;
UPDATE Projects SET Title = 'Προληπτικό αυξητικό αρχείο' WHERE Project_id = 219;
UPDATE Projects SET Title = 'Διασταυρούμενος διαχειριστής λογιστικής πλατφόρμας' WHERE Project_id = 220;
UPDATE Projects SET Title = 'Χρηστοκεντρικός χρήστης που αντιμετωπίζει τον χρήστη γνώσης' WHERE Project_id = 221;
UPDATE Projects SET Title = 'Παραλληλισμός με γνώμονα τον πελάτη με βάση τη λειτουργία' WHERE Project_id = 222;
UPDATE Projects SET Title = 'Βελτιωμένη βελτιστοποίηση αναφοράς' WHERE Project_id = 223;
UPDATE Projects SET Title = 'Πίνακες με γνώμονα την ποιότητα και τη ζήτηση' WHERE Project_id = 224;
UPDATE Projects SET Title = 'Κατανεμημένο περιφερειακό υλικολογισμικό' WHERE Project_id = 225;
UPDATE Projects SET Title = 'Ανοιχτή αρχιτεκτονική και φρέσκια σκέψη του εργατικού δυναμικού' WHERE Project_id = 226;
UPDATE Projects SET Title = 'Αντικειμενοστραφές έργο προσανατολισμένο στη λύση' WHERE Project_id = 227;
UPDATE Projects SET Title = 'Αυτοδύναμο νευρωνικό δίκτυο πολλαπλών εργασιών' WHERE Project_id = 228;
UPDATE Projects SET Title = 'Πλήρως παραμετροποιήσιμη μηδενική διοικητική ιεραρχία' WHERE Project_id = 229;
UPDATE Projects SET Title = 'Βελτιστοποιημένη ουδέτερη τυποποίηση' WHERE Project_id = 230;
UPDATE Projects SET Title = 'Προσαρμόσιμη ριζοσπαστική λύση διαδικτύου' WHERE Project_id = 231;
UPDATE Projects SET Title = 'Ευέλικτο ενδιάμεσο σύνολο εντολών' WHERE Project_id = 232;
UPDATE Projects SET Title = 'Πολυεπίπεδη συσσωμάτωση σε πραγματικό χρόνο' WHERE Project_id = 233;
UPDATE Projects SET Title = 'Πολυεπίπεδη ευρετική μήτρα' WHERE Project_id = 234;
UPDATE Projects SET Title = 'Διαχειριζόμενο ολιστικό ενδοδίκτυο' WHERE Project_id = 235;
UPDATE Projects SET Title = 'Συνεργιστική μεθοδική τυποποίηση' WHERE Project_id = 236;
UPDATE Projects SET Title = 'Προσαρμοστική συστημική εγκατάσταση' WHERE Project_id = 237;
UPDATE Projects SET Title = 'Επαναπροσδιορισμένο μεθοδικό έργο' WHERE Project_id = 238;
UPDATE Projects SET Title = 'Αυτοματοποιημένη κατευθυντική γραφική διεπαφή' WHERE Project_id = 239;
UPDATE Projects SET Title = 'Οραματικό intranet 4ης γενιάς' WHERE Project_id = 240;
UPDATE Projects SET Title = 'Κατανεμημένη λύση διαδικτύου 24/7' WHERE Project_id = 241;
UPDATE Projects SET Title = 'Πολυεπίπεδη διδακτική πρόκληση' WHERE Project_id = 242;
UPDATE Projects SET Title = 'Βελτιωμένη άυλη γραφική διεπαφή χρήστη' WHERE Project_id = 243;
UPDATE Projects SET Title = 'Αναβαθμίσιμη ασύγχρονη εγκατάσταση' WHERE Project_id = 244;
UPDATE Projects SET Title = 'Ευέλικτες μήτρες κατεύθυνσης' WHERE Project_id = 245;
UPDATE Projects SET Title = 'Ιστοσελίδα προσανατολισμένη στο όραμα' WHERE Project_id = 246;
UPDATE Projects SET Title = 'Απο-σχεδιασμένη πρωτοβουλία ανοδικής τάσης' WHERE Project_id = 247;
UPDATE Projects SET Title = 'Εστιασμένη στάση με βάση το περιεχόμενο' WHERE Project_id = 248;
UPDATE Projects SET Title = 'Πολυεπίπεδη υβριδική συνέργεια' WHERE Project_id = 249;
UPDATE Projects SET Title = 'Συμβατό στατικό υλικό' WHERE Project_id = 250;
UPDATE Projects SET Title = 'Προληπτικό αρχείο προστιθέμενης αξίας' WHERE Project_id = 251;
UPDATE Projects SET Title = 'Κλωνοποιημένη εκτελεστική ομάδα εργασίας' WHERE Project_id = 252;
UPDATE Projects SET Title = 'Διασυνοριακός κόμβος υποβάθρου' WHERE Project_id = 253;
UPDATE Projects SET Title = 'Αποκεντρωμένο μεγιστοποιημένο ανοικτό σύστημα' WHERE Project_id = 254;
UPDATE Projects SET Title = 'Εστιασμένη βάση δεδομένων με βάση το πλαίσιο' WHERE Project_id = 255;
UPDATE Projects SET Title = 'Αυτοματοποιημένη ρητή λύση' WHERE Project_id = 256;
UPDATE Projects SET Title = 'Ριζοσπαστικές λειτουργίες ανοικτού κώδικα' WHERE Project_id = 257;
UPDATE Projects SET Title = 'Θεμελιώδης πυρήνας φρέσκιας σκέψης' WHERE Project_id = 258;
UPDATE Projects SET Title = 'Αντιδραστικός παραλληλισμός κρίσιμης αποστολής' WHERE Project_id = 259;
UPDATE Projects SET Title = 'Εκτεταμένος συνεκτικός αναλυτής' WHERE Project_id = 260;
UPDATE Projects SET Title = 'Ομοιογενής λειτουργία πολλαπλών ομάδων' WHERE Project_id = 261;
UPDATE Projects SET Title = 'Υποστήριξη με γνώμονα την ποιότητα' WHERE Project_id = 262;
UPDATE Projects SET Title = 'Πολυμερής μόχλευση υψηλού επιπέδου' WHERE Project_id = 263;
UPDATE Projects SET Title = 'Εναλλασσόμενη τεχνολογία αιχμής' WHERE Project_id = 264;
UPDATE Projects SET Title = 'Συμμαχία με φρέσκια σκέψη με αντίστροφη μηχανική' WHERE Project_id = 265;
UPDATE Projects SET Title = 'Ποικίλο μεθοδικό τοπικό δίκτυο' WHERE Project_id = 266;
UPDATE Projects SET Title = 'Οραματική πύλη πλήρους φάσματος' WHERE Project_id = 267;
UPDATE Projects SET Title = 'Κεντρικός αναλυτής μηδενικής ανοχής' WHERE Project_id = 268;
UPDATE Projects SET Title = 'Ενισχυμένη ενορχήστρωση με δυνατότητα διαδικτύου' WHERE Project_id = 269;
UPDATE Projects SET Title = 'Πολυπλοκότητα 5ης γενιάς με επίκεντρο την ποιότητα' WHERE Project_id = 270;
UPDATE Projects SET Title = 'Εφαρμοσμένη συστηματική πρόβλεψη' WHERE Project_id = 271;
UPDATE Projects SET Title = 'Παρακολουθούμενη τυποποίηση ενεργοποίησης' WHERE Project_id = 272;
UPDATE Projects SET Title = 'Αυτόνομη δομή τιμολόγησης πελάτη-εξυπηρετητή' WHERE Project_id = 273;
UPDATE Projects SET Title = 'Κλωνοποιημένη συστοιχία ομοιόμορφων αξόνων' WHERE Project_id = 274;
UPDATE Projects SET Title = 'Προσαρμόσιμος οικοκεντρικός πυρήνας' WHERE Project_id = 275;
UPDATE Projects SET Title = 'Επεκταμένο εξωδικτυακό δίκτυο' WHERE Project_id = 276;
UPDATE Projects SET Title = 'Συγχρονισμένη τοπική πολιτική' WHERE Project_id = 277;
UPDATE Projects SET Title = 'Δικτυωμένη αμοιβαία πρωτοβουλία' WHERE Project_id = 278;
UPDATE Projects SET Title = 'Δικτυωμένη λύση 6ης γενιάς' WHERE Project_id = 279;
UPDATE Projects SET Title = 'Σπονδυλωτό μοντέλο βάσης δεδομένων' WHERE Project_id = 280;
UPDATE Projects SET Title = 'Προοδευτική πρωτοβουλία 4ης γενιάς' WHERE Project_id = 281;
UPDATE Projects SET Title = 'Αφομοιωμένοι πίνακες με βάση τις ανάγκες' WHERE Project_id = 282;
UPDATE Projects SET Title = 'Καινοτόμος λύση διαδικτύου με παρακολούθηση του εύρους ζώνης' WHERE Project_id = 283;
UPDATE Projects SET Title = 'Τυποποίηση με γνώμονα τη ζήτηση' WHERE Project_id = 284;
UPDATE Projects SET Title = 'Πολωτική μεγιστοποιημένη συσσωμάτωση' WHERE Project_id = 285;
UPDATE Projects SET Title = 'Διασταυρούμενη εγκατάσταση κινητής τηλεφωνίας' WHERE Project_id = 286;
UPDATE Projects SET Title = 'Φιλική προς το χρήστη βάση δεδομένων στελεχών' WHERE Project_id = 287;
UPDATE Projects SET Title = 'Ισορροπημένο πρωτόκολλο δημόσιου κλειδιού' WHERE Project_id = 288;
UPDATE Projects SET Title = 'Θεμελιώδες υλικό ευαίσθητο στο πλαίσιο' WHERE Project_id = 289;
UPDATE Projects SET Title = 'Προσανατολισμένοι στον πελάτη ρητοί πίνακες' WHERE Project_id = 290;
UPDATE Projects SET Title = 'αφομοιωμένη διαχείριση του προϋπολογισμού ανθρώπινων πόρων' WHERE Project_id = 291;
UPDATE Projects SET Title = 'Βελτίωση συνεκτικών διαδικασιών ανοικτού κώδικα' WHERE Project_id = 292;
UPDATE Projects SET Title = 'Συμμαχία με ανοικτή αρχιτεκτονική με δυνατότητα πλέγματος' WHERE Project_id = 293;
UPDATE Projects SET Title = 'Αναπροσαρμοσμένη υλικοτεχνική συμμαχία' WHERE Project_id = 294;
UPDATE Projects SET Title = 'Επαναπροσδιορισμένη απόδοση ανθρώπινων πόρων' WHERE Project_id = 295;
UPDATE Projects SET Title = 'Οργανικό ενδιάμεσο μοντέλο' WHERE Project_id = 296;
UPDATE Projects SET Title = 'Αντίστροφη δομή τιμολόγησης μηδενικού ελαττώματος' WHERE Project_id = 297;
UPDATE Projects SET Title = 'Επίμονοι διχασμένοι διαμεσολαβητές πληροφοριών' WHERE Project_id = 298;
UPDATE Projects SET Title = 'Εργονομική ευρετική βάση δεδομένων' WHERE Project_id = 299;
UPDATE Projects SET Title = 'Προοδευτικό διακριτό λογισμικό' WHERE Project_id = 300;