insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Stavros Niarchos Foundation','SNF',17674,'Syggrou Avenue 100','Athens','FIRM', 100000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('VP Foundation','VP',16122,' Voutza 9','Athens','FIRM',156000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('GK Organisation','GKO',15771,'Oulof Palme 78','Athens','RESEARCH CENTER',230000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('National Technical University of Athens','NTUA',15780,'Hr.Polytexneioy 3','Athens','UNIVERSITY',700000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('National Kapodistrian University of Athens','NKUA',15772,'Odos Panipistimioupolhs','Athens','UNIVERSITY',500000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('GPF Research Center','GPP',16122,'Voutza 18','Athens','RESEARCH CENTER',150000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Science and Technology Research Center','STRC',54627,'Monasthriou 97','Thessaloniki','RESEARCH CENTER',10800);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Aristoteleion University Thessaloniki ','AUTH',54636,'Egnatias 80','Thessaloniki','UNIVERSITY',120000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Athens University of Economics and Buisness','AUEB',10434,'28hs Oktwmvriou 45','Athens','UNIVERSITY',170000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('G&G Foundation','G&G',16122,'2as Maiou 76','Athens','FIRM',50000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Techonological Research Center of Patras','TRCP',26221,'Hfaistoy 14','Patras','RESEARCH CENTER',137000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('University of Patras','UoP',26504,'Erasmou 41','Patras','UNIVERSITY',300000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('MP Foundation of Technology','MPF',262221,'El.Venizeloy 37','Patras','FIRM',59000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('University of Ioannina','UoI',45110,'Leoforos Stavrou Niarchou 98','Ioannina','UNIVERSITY',100700);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Ioannina Institute of Technology','IIT',45110,'Zwsimadwn 43','Ioannina','RESEARCH CENTER',600000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Panepistimio Dutikhs Elladas','UoWG',30131,'Ag,Iwannoy Rhgana 56','Agrinio','UNIVERSITY',20000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('CT Institute of Research','CTIR',30130,'Xarilaoy Trikouph 25','Agrinio','RESEARCH CENTER',90000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Atnens Institute of Advanced Technology','AIoAT',11474,'Leoforos Alexandras 117','Athens','RESEARCH CENTER',900000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('University of Crete','UoC',70013,'Andrea Kalokairinoy 34','Hrakleion','UNIVERSITY',140000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('P&M Organization Hrakleion','P&M',71304,'Therisoy 18','Hrakleion','FIRM',130000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('University of Peireus','UNIPEI',18534,'Karaolh kai Dhmhtrioy 78','Athens','UNIVERSITY',120000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Univerity of West Athens','UoWA',12243,'AG,Spuridwnos 61','Athens','UNIVERSITY',80000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('ALKA Institute of Development','ALKA',10443,'Rodou 5','Athens','RESEARCH CENTER',123000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Central Athens Art Institute','CAAI',11851,'Kritolaiou 49','Athens','RESEARCH CENTER',50000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('ROSPI & Co.','RSP',10554,'Aiswpou 90','Athens','FIRM',690000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Nayplio Insitute of Research','NIR',21100,'Argous 43','Nayplio','RESEARCH CENTER',170000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Mykonos Research Center','MRC',84600,'Skardana 17','Mykonos','RESEARCH CENTER',1300000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('GG Firm and Co.','GGF',55133,'Pontou 9','Thessaloniki','FIRM',450000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('FT Foundation','FTF',16122,'Voutza 33','Athens','FIRM',135000);
insert into Organization (`name`,`sort_name`,`TK`,`street`,`city`,`Type`,`Budget`) values('Univesity of Peloponesse','UoKA',24100,'Kallipateiras 67','Kalamata','UNIVERSITY',235000);