INSERT INTO `Program` (`name`,`sector`) VALUES ('Environmental Preservation Program','Environmental sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Database Development Program','IT sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Recycling Program','Environmental sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Pharmaceutical Research Program','Biology sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Light and Lasers Technologies Program','Technologies sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Machine Learning Program','IT sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Renewable Energy Sources Program','Environmental sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Algorithms Program','Mathemetics sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Law Enforcement Program','Law sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Road Development Program','Infrastracture sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Building Preservation','Infrastracture sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Wind Park Development Program','Environmental sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Water Waste Reduction Program','Biology sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Earthquake Research Program','Enviromental sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Artificial Inteligence Development Program','IT sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Solar Energy Ifrastructure Program','Environmental sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Mathematics Department Update Program','Mathemetics sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Biological Crop Facilities Program','Enviromental sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Advanced Technologies Program','Technologies sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Software Development Program','IT sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Recycling Materials Program','Environmental sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Microbiologies Technologies Program','Biology sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('National Parks Renovation Program','Enviromental sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Computer Applications on Arcitecture Program','IT sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Neural Networks Program','Technologies sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Robotic Facilities Program','Technologies sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Modern Antennas Program','Technologies sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('National Forests Preservation Program','Environmental sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Advanced Database Systems Development Program','IT sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Applied Robotics Technologies Program','Technologies sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Viruses and Pandemics Program','Biology sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('New Enhanced Performance Technologies Program','Technologies sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Software for Smart Cars Program','IT sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Smart Cities Program','Environmental sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Applied Mathemetics Program','Mathemetics sector');
INSERT INTO `Program` (`name`,`sector`) VALUES ('Transportation Infrastracture Program','Technologies sector');