select Projects.Title, Projects.start_date, Projects.end_date, Field.name from ((Projects join Projects_has_Field on Projects.Project_id = Projects_has_Field.Project_id) join Field on Field.Field_id = Projects_has_Field.Field_id) where Field.name = 'Maths' and Projects.end_date > NOW();

select Researcher.first_name, Researcher.last_name from ((Projects join Projects_has_Field on Projects.Project_id = Projects_has_Field.Project_id) join Field on Field.Field_id = Projects_has_Field.Field_id join Researcher_works_on_Projects on Projects.Project_id = Researcher_works_on_Projects.Project_id join Researcher on Researcher.Researcher_id = Researcher_works_on_Projects.Researcher_id) where Field.name = '' and Projects.end_date > NOW();

with temp2(Field1, Field2,TotalBudget) as (with temp(Project_id,F1,F2) as (select Pr.Project_id, Pr.Field_id ,P.Field_id from (Projects_has_Field as P join Projects_has_Field as Pr on Pr.Project_id = P.Project_id) where (Pr.Field_id < P.Field_id)) select temp.F1, temp.F2, sum(Budget) from temp join Projects on temp.Project_id = Projects.Project_id group by temp.F1, temp.F2) select f1.name as "Field 1", f2.name as "Field 2", temp2.TotalBudget as "Total Budget" from temp2 join (Field as f1 join Field as f2 on f1.Field_id < f2.Field_id) on f1.Field_id = temp2.Field1 and f2.Field_id = temp2.Field2 order by temp2.TotalBudget DESC LIMIT 5;

select Researcher.Researcher_id,Researcher.first_name, Researcher.last_name,TIMESTAMPDIFF(YEAR,Researcher.date_of_birth,NOW()),COUNT(*) FROM (Researcher join Researcher_works_on_Projects on Researcher_works_on_Projects.Researcher_id = Researcher.Researcher_id) WHERE TIMESTAMPDIFF(YEAR,Researcher.date_of_birth,NOW()) < 40 GROUP BY Researcher.Researcher_id order by COUNT(*) DESC;

select Executive.Executive_id, Executive.first_name, Executive.last_name, SUM(Projects.Budget) from (Executive join Projects on Projects.Executive_id = Executive.Executive_id) join Organization on Organization.Organization_id = Projects.Organization_id where Organization.Type = 'FIRM' group by Executive.Executive_id order by SUM(Projects.Budget) DESC;

select  Researcher.Researcher_id,Researcher.first_name, Researcher.last_name,COUNT(*) as cnt from (Researcher join Researcher_works_on_Projects on Researcher.Researcher_id = Researcher_works_on_Projects.Researcher_id) where Researcher_works_on_Projects.Project_id not in (select Project_id from Deliverable) group by Researcher.Researcher_id  having COUNT(*) > 4 order by COUNT(*) DESC;

with temp as(select Organization.Organization_id as org, Organization.name as name, YEAR(Projects.start_date) as year, COUNT(*) as cnt from (Projects join Organization on Projects.Organization_id = Organization.Organization_id) group by Organization.Organization_id, YEAR(Projects.start_date) order by Organization.Organization_id, YEAR(Projects.start_date)) select t1.org, t1.name, t1.year as str, t2.year as end, t1.cnt from temp as t1, temp as t2 where t1.year = t2.year -1  and t1.cnt = t2.cnt and t2.cnt > 9 and t1.org = t2.org order by t1.org, t1.year;

select Researcher.Researcher_id,Researcher.first_name, Researcher.last_name,Field.name from (Researcher join Researcher_works_on_Projects on Researcher.Researcher_id = Researcher_works_on_Projects.Researcher_id) join (Projects_has_Field on Projects_has_Field.Project_id = Researcher_works_on_Projects.Project_id) join (Field on Field.Field_id = Projects_has_Field.Field_id) WHERE Field.name = '';